=== ProPra16/programmierpraktikum-abschlussprojekt-the-fellowship-of-the-string/excercises.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT excercises (exercise)+>
<!ELEMENT exercise (description, classes, tests, config)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT classes (class)+>
<!ELEMENT class (#PCDATA)>
<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT tests (test)>
<!ELEMENT test (#PCDATA)>
<!ATTLIST test name CDATA #REQUIRED>

<!ELEMENT config (babysteps, timetracking)>
<!ELEMENT babysteps EMPTY>
<!ATTLIST babysteps value CDATA #REQUIRED seconds CDATA #REQUIRED>

<!ELEMENT timetracking EMPTY>
<!ATTLIST timetracking value CDATA #REQUIRED>

=== ProPra16/programmierpraktikum-abschlussprojekt-the-fellowship-of-the-string/KatalogBSP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE KatalogBSP SYSTEM "excercises.dtd">
<excercises>
<exercise>
<description>
Simple Hello World
</description>
<classes>
<class name="hello">
public class hello {
	public static void main(String[] args){
	System.out.println("Hello World");
	}
}
</class>
</classes>
<tests>
<test name="HelloTest">
import static org.junit.Assert.*;
import org.junit.Test;
public class RomanNumbersTest {
	@Test
	public void testSomething() {
	}
}
</test>
</tests>
<config>
<babysteps value="true" />
<timetracking value="false" />
</config>
</exercise>
</excercises>
